services:
  smtp:
    build:
      context: .
      dockerfile: Dockerfile.smtp
    environment:
      - SERVER_HOST=${SMTP_INTERNAL_SERVER_HOST}
      - SERVER_PORT=${SMTP_INTERNAL_SERVER_PORT}
      - SMTP_DOMAIN_NAME=${SMTP_DOMAIN_NAME}
      - SMTP_LOGIN_ID=${SMTP_LOGIN_ID}
      - SMTP_LOGIN_PASSWORD=${SMTP_LOGIN_PASSWORD}
      - MESSAGE_ID_DOMAIN=${SMTP_MESSAGE_ID_DOMAIN}
      - JSON_LOGGER=${SMPT_JSON_LOGGER}
    ports:
      - "${SMTP_PORT}:${SMTP_INTERNAL_SERVER_PORT}"
    command: [ "relayer-smtp" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${SMTP_INTERNAL_SERVER_PORT}/api/ping" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  imap:
    build:
      context: .
      dockerfile: Dockerfile.imap
    environment:
      - RELAYER_ENDPOINT=http://host.docker.internal:${RELAYER_PORT}/prover/signAndSend
      - IMAP_LOGIN_ID=${IMAP_LOGIN_ID}
      - IMAP_LOGIN_PASSWORD=${IMAP_LOGIN_PASSWORD}
      - IMAP_DOMAIN_NAME=${IMAP_DOMAIN_NAME}
      - IMAP_PORT=${IMAP_PORT}
      - AUTH_TYPE=${IMAP_AUTH_TYPE}
      - JSON_LOGGER=${IMAP_JSON_LOGGER}
    command: [ "cargo", "run" ]
